### ISSUE TITLE
在使用python 3.7.16时zhipu ai引入错误

### ISSUE THREAD

**Issue by Ningreka** [MetaGLM/zhipuai-sdk-python-v4#37]
环境使用最新python 3.7版本时，引入zhipuai报错。具体版本是python 3.7.16
```shell
>>> from zhipuai import ZhipuAI
Traceback (most recent call last):
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/core/_base_compat.py", line 218, in <module>
    from functools import cached_property as cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/home/ningc/.conda/envs/zhipu/lib/python3.7/functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/__init__.py", line 2, in <module>
    from ._client import ZhipuAI
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/_client.py", line 7, in <module>
    from .core import _jwt_token
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/core/__init__.py", line 1, in <module>
    from ._base_models import (
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/core/_base_models.py", line 22, in <module>
    from ._utils import is_list, is_mapping, parse_date, parse_datetime
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/core/_utils/__init__.py", line 2, in <module>
    from ._utils import (
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/core/_utils/_utils.py", line 24, in <module>
    from .._base_compat import parse_date as parse_date, parse_datetime as parse_datetime
  File "/home/ningc/.conda/envs/zhipu/lib/python3.7/site-packages/zhipuai/core/_base_compat.py", line 220, in <module>
    from cached_property import cached_property as cached_property
ModuleNotFoundError: No module named 'cached_property'
```
具体原因就是`from functools import cached_property as cached_property`这个python3.8开始的模块

但是文档里面说支持python>=3.7，所以可能是哪里忘了？

**Comment by glide-the** [comment]
最新的版本调整了api，目前正式sdk支持 Python (3.8, 3.9, 3.10, 3.11, 3.12)
