### ISSUE TITLE
安装后推理报错

### ISSUE THREAD

**Issue by 128Ghe980** [MetaGLM/zhipuai-sdk-python-v4#5]
以下为报错：
Traceback (most recent call last):
  File "/home/tione/notebook/code/Qwen-main/output_qwen/eval_summary.py", line 12, in <module>
    from zhipuai import ZhipuAI
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/__init__.py", line 2, in <module>
    from ._client import ZhipuAI
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/_client.py", line 9, in <module>
    from .core._http_client import HttpClient, ZHIPUAI_DEFAULT_MAX_RETRIES
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 21, in <module>
    from ._request_opt import ClientRequestParam, UserRequestInput
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_request_opt.py", line 25, in <module>
    class ClientRequestParam(pydantic.BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'zhipuai.core._base_type.NotGiven'>, see `arbitrary_types_allowed` in Config
是有其他依赖包没安装吗？

**Comment by Neptune-0724** [comment]
请问你解决了没有🙋

**Comment by zRzRzRzRzRzRzR** [comment]
使用pydantic 2.5以上版本
